import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:provider/provider.dart';
import 'model/provider/profile_setup_provider.dart';
import 'view/splash_screen.dart';
import 'database_service.dart';
import 'model/provider/user_provider.dart';
import 'package:geolocator/geolocator.dart';
import 'controller/location_helper.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by 'flutterfire configure'
import 'controller/firebase_messaging_service.dart';

final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();
Position? globalTempLocation;
String? globalFcmToken;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await dotenv.load(fileName: ".env"); // Load environment variables
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // INITIALIZE NOTIFICATIONS (FCM + Local)
  // We initialize the Firebase Messaging Service here. Inside FirebaseMessagingService, it should call NotificationService().initNotification()
  final fcmService = FirebaseMessagingService.instance();
  await fcmService.init();
  try {
    globalFcmToken = await fcmService.getToken();
    print("Global FCM Token Loaded: $globalFcmToken");
  } catch (e) {
    print("Failed to get FCM Token: $e");
  }

  final userProvider = UserProvider();
  await userProvider.loadUserFromPrefs(); // Load from local storage

  try {
    globalTempLocation = await LocationHelper.determinePosition();
    print("Initial Location Fetched: Lat: ${globalTempLocation?.latitude}, Lng: ${globalTempLocation?.longitude}");
  } catch (e) {
    print("Could not fetch initial location: $e");
  }

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider<UserProvider>.value(value: userProvider),
        ChangeNotifierProvider(create: (_) => ProfileSetupProvider()),
      ],
      child: const MyApp(), // This should be inside MultiProvider
    ),
  );
}


class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with WidgetsBindingObserver {
  final DatabaseConnection _db = DatabaseConnection();

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.detached) {
      _db.close();  // Always closes regardless of current screen
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: navigatorKey,
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        fontFamily: 'Inter',
      ),
      // Normal launch: no notification, so pass nulls
      home: const SplashScreen(
        fromNotification: false,
        notificationId: null,
      ),
    );
  }
}
